version: '3.7'

services:

  naiveproxy-server:
    image: naiveproxy:server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/naiveproxy:/naiveproxy:ro
      - ./data/naiveproxy/caddy-hidden-dir:/root/.caddy
      - ./data/camouflage/public:/naiveproxy/caddy/public
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
